sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t blueridge/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true blueridge/docker-react npm run test